### ISSUE TITLE
Not working with Ruby 1.9

### ISSUE THREAD

**Issue by ghost** [philc/textmatevim#2]
Hey there-

Oh, my excitement for this bundle......

BUT. It doesn't seem to work at all. I can't type anything.

TextMate  Version 1.5.10 (1631)

I deleted all other bundles and the preferences as well.

**Comment by philc** [comment]
Hey dsr, let's do some troubleshooting.

Can you quit TextMate, open the Console app, launch TextMate again, and try typing something? Scan the log entries from TextMate which are going into Console and see if you see anything suspicious. Also, append /tmp/textmatevim.log to this bug.

**Comment by ghost** [comment]
From Console.app:

3/25/11 1:43:38 PM  TextMate[52887] 8096nable to read response from event_handler.rb!
3/25/11 1:43:38 PM  TextMate[52887] 8096nable to read response from event_handler.rb!
3/25/11 1:43:38 PM  TextMate[52887] -[OakTextView <null selector>]: unrecognized selector sent to instance 0x15738040
3/25/11 1:43:38 PM  TextMate[52887] -[OakTextView <null selector>]: unrecognized selector sent to instance 0x15738040

I don't seem to have a /tmp/textmatevim.log....

**Comment by philc** [comment]
Hey Dan, which version of OSX and TextMate are you running?

It looks like event_handler.rb is not being started. Can you try running it manually using ruby to see if there are any conspicuous startup errors?

cd ~/Library/Application\ Support/TextMate/PlugIns/TextMateVim.tmplugin/Contents/Resources/

ruby event_handler.rb

Do you know if you have anything peculiar/custom in your ruby environment?

**Comment by ghost** [comment]
I'm on 10.6.7.

I do have ruby 1.9.2 installed in /usr/local/bin but I point TM_RUBY to /usr/bin/ruby to avoid potential complications.

If I start with /usr/bin/ruby it just sits there; no output.

If I use ruby (which points to ruby 1.9.2) I get:

event_handler.rb:53: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n'
    when "keydown": handle_keydown_message(message_json)
                   ^
event_handler.rb:54: syntax error, unexpected keyword_when, expecting keyword_end
    when "getKeybindings": handle_get_keybindings_message
        ^
event_handler.rb:54: syntax error, unexpected ':', expecting keyword_end
    when "getKeybindings": handle_get_keybindings_message
                          ^
event_handler.rb:154: syntax error, unexpected keyword_end, expecting $end

**Comment by ghost** [comment]
Crap. TextMate Version 1.5.10 (1631). Sorry.

**Comment by philc** [comment]
Ah ha; ruby 1.9. I'll get a fix in.

**Comment by ghost** [comment]
It's not respecting the TextMate TM_RUBY?

**Comment by philc** [comment]
It is not, unfortunately, due to technical limitations. The easier fix is to make textmatevim work in ruby19, which it should anyway. That should be relatively quick.

**Comment by ghost** [comment]
Cool. I will anxiously await the fix.

**Comment by philc** [comment]
98604790a01ebcd5313c9589f08e984c783d48e1 makes the code base ruby 1.9 compatible. Give it a shot and let me know if this does the trick.

**Comment by ghost** [comment]
Seems to be working now. Thanks Phil!

I'll let you know if I run into any problems.

**Comment by philc** [comment]
Sweet. Thanks for the bug report! I'll fold ruby19 support into a prebuilt release shortly.

**Comment by ghost** [comment]
I have been seeing some display issues, but I haven't nailed down what causes it.

<C-v> stops highlighting and the cursor stops changing between modes.

**Comment by philc** [comment]
Do you have any other textmate plugins active?

**Comment by ghost** [comment]
Just MissingDrawer. There is a Green Moleskine package that I use that modifies a bunch of ui stuff as well.

**Comment by philc** [comment]
I'll give each of those extensions a try to see if they jack up the cursor for me as well. Let me know if you can isolate the conditions under which it stops working correctly.

**Comment by ghost** [comment]
Will do.

**Comment by philc** [comment]
hey dsr, Ruby 1.9 support is now rolled into the latest released binary. Thanks again for reporting it.

Regarding the glitchy cursor display, I installed MissingDrawer and the green moleskine plugins but haven't been able to reproduce the problem you described. Can you tell me precisely which plugins you have installed by doing this:
ls ~/Library/Application\ Support/TextMate/PlugIns/

Also, if you can reliably reproduce it, can you tell me if you're editing files which are revision controlled, and what kind of files? (e.g. python, ruby). Thanks.

**Comment by ghost** [comment]
Here's the output:

MissingDrawer.tmplugin  TextMateVim.tmplugin

I haven't been able to reproduce it, unfortunately (or fortunately, depending on how you look at it I guess).
